name: General Feature Request 💡
description: Have a new idea/feature for Project Please suggest!
title: "[FEATURE] <description>"
labels: ["⭐ goal: addition", "🚦 status: awaiting triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?
    validations:
      required: false
     - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing issues"
          required: true

        - label: "I have read the [Contributing Guidelines]
          required: true

        - label: "I am willing to work on this issue (optional)"
          required: false

        - label: "I am a GSSoC'23 contributor"
          required: false 
